title: English - The Global Language
email: 
description: English is known as the Global Language for good reason.

baseurl: "/"
url: http://keralahost.in/englishtutors
google_adsense: Your-adsense-code

markdown: kramdown

name: English - The Global Language

date: 2019-04-17 03:56:19 +0000
permalink: /:year/:month/:day/:title

logo: false
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://keralahost.in/englishtutors/
google_analytics: UA-31XXXXXX-X
gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: 
author_image: 

author: Murphy Brown
